# Generated by Django 4.2.16 on 2024-11-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customer_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
