# Generated by Django 4.2.16 on 2024-11-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birth',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
