# Generated by Django 4.2.16 on 2024-11-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_birth_alter_customer_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(default='2000-01-01', null=True),
        ),
    ]
