# Generated by Django 4.2.16 on 2024-11-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_customer_id_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='rafta@test.com', max_length=254),
        ),
    ]
