# Generated by Django 4.2.16 on 2024-11-21 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customer_user'),
        ('services', '0003_resquest_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resquest_service',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
