# Generated by Django 4.2.16 on 2024-11-21 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_resquest_service_intervall_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resquest_service',
            old_name='intervall',
            new_name='interval',
        ),
        migrations.RemoveField(
            model_name='resquest_service',
            name='customer',
        ),
        migrations.AddField(
            model_name='resquest_service',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
