# Generated by Django 4.2.16 on 2024-11-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_resquest_service_date_alter_resquest_service_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resquest_service',
            name='service',
        ),
        migrations.AddField(
            model_name='resquest_service',
            name='username',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
