# Generated by Django 4.2.16 on 2024-11-21 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0008_remove_resquest_service_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resquest_service',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='resquest_service',
            name='username',
        ),
        migrations.AddField(
            model_name='resquest_service',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
