# Generated by Django 4.2.16 on 2024-11-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_resquest_service_adress_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resquest_Service',
        ),
    ]
