# Generated by Django 4.2.16 on 2024-11-22 08:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_customer_id_alter_customer_user'),
        ('services', '0010_delete_resquest_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('interval', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_service', to='users.customer')),
            ],
        ),
    ]
