# Generated by Django 4.2.16 on 2024-11-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_requestservicemodel_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestservicemodel',
            name='company',
            field=models.CharField(default='Default Company', max_length=50),
        ),
        migrations.AddField(
            model_name='requestservicemodel',
            name='custom_field',
            field=models.CharField(default='souillon', max_length=50),
        ),
        migrations.AddField(
            model_name='requestservicemodel',
            name='name',
            field=models.CharField(default='rafta', max_length=50),
        ),
        migrations.AddField(
            model_name='requestservicemodel',
            name='request_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
