# Generated by Django 4.2.16 on 2024-11-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_requestservicemodel_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestservicemodel',
            name='company',
            field=models.CharField(default='zk12', max_length=50),
        ),
    ]
