# Generated by Django 4.2.16 on 2024-11-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_requestservicemodel_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestservicemodel',
            name='description',
            field=models.CharField(default='Default Company', max_length=150),
        ),
    ]
