# Generated by Django 4.2.16 on 2024-11-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_requestservicemodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestservicemodel',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
