# Generated by Django 4.2.16 on 2024-11-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_requestservicemodel_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestservicemodel',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
