# Generated by Django 4.2.16 on 2024-11-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_requestservicemodel_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestservicemodel',
            name='job_name',
            field=models.CharField(default='Masson', max_length=50),
        ),
        migrations.AlterField(
            model_name='requestservicemodel',
            name='description',
            field=models.CharField(default='nothing here', max_length=150),
        ),
    ]
