# Generated by Django 4.2.16 on 2024-11-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_alter_requestservicemodel_company'),
        ('services', '0017_requestservicemodel_job_name_and_more'),
    ]

    operations = [
    ]
