# Generated by Django 4.2.16 on 2024-11-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_merge_20241122_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestservicemodel',
            name='company',
            field=models.CharField(default='Default Company', max_length=50),
        ),
    ]
